const GENERAL_GAME_SCORE = {
    DEFAULT_SCORE: 0,
    WIN: 2,
    LOSE: 0,
};

const SPY_GAME_SCORE = {
    // WIN: 2,
    // LOSE: -1,
};

const DRAWING_GAME_SCORE = {
    DEFAULT_SCORE: GENERAL_GAME_SCORE.DEFAULT_SCORE,
    GUESS_RIGHT: GENERAL_GAME_SCORE.WIN,
    GUESS_WRONG: GENERAL_GAME_SCORE.LOSE,
    WIN_TOP1: GENERAL_GAME_SCORE.WIN * 4,
    WIN_TOP2: GENERAL_GAME_SCORE.WIN * 3,
    WIN_TOP3: GENERAL_GAME_SCORE.WIN * 2,
    WIN_TOP4: GENERAL_GAME_SCORE.WIN * 1.5,
    WIN_TOP5: GENERAL_GAME_SCORE.WIN,
    WIN_TOP6: GENERAL_GAME_SCORE.WIN * 0.5,
};

export { SPY_GAME_SCORE, DRAWING_GAME_SCORE, GENERAL_GAME_SCORE };