const GENERAL_GAME_SCORE = {
    DEFAULT_SCORE: 0,
    WIN: 2,
    LOSE: 0,
};

const SPY_GAME_SCORE = {
    DEFAULT_SCORE: GENERAL_GAME_SCORE.DEFAULT_SCORE,
};

const SPY_GAME_MONEY = {
    SPY_WIN_MONEY: 30,
    CIVILIAN_WIN_MONEY: 15,
    DEFAULT_MONEY: 0,
}

const DRAWING_GAME_SCORE = {
    DEFAULT_SCORE: GENERAL_GAME_SCORE.DEFAULT_SCORE,
    GUESS_RIGHT_SCORE: GENERAL_GAME_SCORE.WIN,
    GUESS_WRONG_SCORE: GENERAL_GAME_SCORE.LOSE,
    WIN_TOP1_SCORE: GENERAL_GAME_SCORE.WIN * 4,
    WIN_TOP2_SCORE: GENERAL_GAME_SCORE.WIN * 3,
    WIN_TOP3_SCORE: GENERAL_GAME_SCORE.WIN * 2,
    WIN_TOP4_SCORE: GENERAL_GAME_SCORE.WIN * 1.5,
    WIN_TOP5_SCORE: GENERAL_GAME_SCORE.WIN,
    WIN_TOP6_SCORE: GENERAL_GAME_SCORE.WIN * 0.5,
};

const DRAWING_GAME_MONEY = {
    WIN_TOP1_MONEY: 15,
    WIN_TOP2_MONEY: 10,
    WIN_TOP3_MONEY: 5,
    DEFAULT_MONEY: 0,
};

export { SPY_GAME_SCORE, DRAWING_GAME_SCORE, GENERAL_GAME_SCORE, SPY_GAME_MONEY, DRAWING_GAME_MONEY };